import type { Metadata } from "next";
import Link from "next/link";

import PageShell from "@/components/site/PageShell";
import Reveal from "@/components/site/Reveal";

export const metadata: Metadata = {
  title: "FAQ",
  description: "Everything people ask about Lumen: how lessons are built, what interruption does, what it costs, and how it stays safe.",
};

const GROUPS: { label: string; items: { q: string; a: string }[] }[] = [
  {
    label: "The product",
    items: [
      {
        q: "Is this just AI-generated video?",
        a: "No — and that's the point. Lumen never renders a video file. The model describes each scene as structured data, and a deterministic engine animates it live in your browser at 60fps. That's why you can interrupt it, and why the math is drawn precisely instead of hallucinated pixel by pixel.",
      },
      {
        q: "What happens when I interrupt?",
        a: "The lesson pauses, Lumen generates a narrated answer scene that's aware of exactly what was on the board, plays it, then resumes the lesson where it left off. Answers take seconds, not minutes, because nothing is re-rendered — one fast model call produces one new scene.",
      },
      {
        q: "What subjects does it cover?",
        a: "Anything that benefits from being drawn: calculus, linear algebra, trigonometry, geometry, physics intuition, probability, algorithms. The rendering engine composes curves, shapes and notation generically, so new topics don't need new engineering.",
      },
      {
        q: "How is a lesson personalized?",
        a: "Before building anything, Lumen asks a few diagnostic questions — your background, what you want out of it, your pace. The teaching script is written against those answers, not a generic audience. The same topic genuinely teaches differently for different people.",
      },
      {
        q: "How long does a lesson take to build?",
        a: "Usually a minute or two for a full multi-beat lesson, and you watch the progress live — script, then scenes, then narration. Interruption answers are much faster, by design: seconds.",
      },
      {
        q: "Can I watch something without building a lesson?",
        a: "Yes — the homepage plays the real engine live, and there's a full hand-authored sample lesson in cinema mode. It's the same renderer that plays every generated lesson.",
      },
    ],
  },
  {
    label: "Quality & correctness",
    items: [
      {
        q: "How do you keep the visuals correct?",
        a: "Geometry is never left to the model. Objects declare relationships — “on this curve at x = 1”, “above that label” — and a deterministic solver computes exact positions. Every scene is then linted for overlaps, off-frame text, and invalid references, and mechanically repaired before it plays.",
      },
      {
        q: "What if the model produces something broken?",
        a: "Its output is validated against a strict schema, out-of-range values are clamped, truncated responses are recovered, and anything undrawable degrades to a correct simpler view. The worst case is a plainer scene — not a broken one.",
      },
      {
        q: "Does it work with sound off?",
        a: "Yes. Captions mirror the narration word-for-word throughout, and the animations are synchronized to the same timeline either way.",
      },
    ],
  },
  {
    label: "Safety & privacy",
    items: [
      {
        q: "Is it safe to run model output in my browser?",
        a: "The model never writes code. It emits a JSON scene description that is validated, capped, and sanitized server-side; a pure TypeScript renderer draws it. The only evaluated strings are math expressions, parsed by a whitelist parser — no eval, ever. Formulas render with injection disabled.",
      },
      {
        q: "Will this melt my laptop?",
        a: "No. Scenes are hard-capped in size and duration, animations use only GPU-friendly properties, and there's no video decoding or WebGL. It's a small SVG scene graph — lighter than most streaming sites.",
      },
      {
        q: "What do you do with my questions?",
        a: "Lesson topics and interruptions are used to build your lessons. During the preview, lessons aren't even persisted server-side — a privacy policy worth reading ships with accounts at public release.",
      },
    ],
  },
  {
    label: "Plans & access",
    items: [
      {
        q: "What does it cost?",
        a: "During the preview: nothing. At public release: a free Learner tier (5 lessons/month), Student at $12/month for unlimited lessons and history, and custom Classroom plans. Pricing is published early so there are no surprises.",
      },
      {
        q: "Why can it be this cheap?",
        a: "No GPU farms, no render queues, no video files. A lesson is compact structured data drawn by your browser, generated by inexpensive models made reliable through engineering. The economics are software economics.",
      },
      {
        q: "Do I need an account?",
        a: "Not during the preview — you can start a lesson immediately. Accounts arrive with the public release for lesson history and syncing.",
      },
    ],
  },
];

export default function FaqPage() {
  return (
    <PageShell
      eyebrow="FAQ"
      title="Questions, answered."
      lede="If yours isn't here, ask us directly — or better, start a lesson and interrupt it with the question."
    >
      <div className="space-y-16">
        {GROUPS.map((g, gi) => (
          <section key={g.label} className="grid gap-8 lg:grid-cols-[16rem_1fr]">
            <Reveal delay={Math.min(gi * 0.05, 0.15)}>
              <h2 className="eyebrow">{g.label}</h2>
            </Reveal>
            <Reveal delay={Math.min(gi * 0.05, 0.15)} className="divide-y divide-hairline border-y border-hairline">
              {g.items.map((f) => (
                <details key={f.q} className="group py-5">
                  <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-[0.95rem] font-medium [&::-webkit-details-marker]:hidden">
                    {f.q}
                    <span aria-hidden className="font-mono text-lg leading-none text-faint transition-transform duration-200 group-open:rotate-45">
                      +
                    </span>
                  </summary>
                  <p className="mt-3 pr-8 text-sm leading-7 text-muted">{f.a}</p>
                </details>
              ))}
            </Reveal>
          </section>
        ))}
      </div>

      <Reveal className="mt-20 flex flex-col items-center gap-4 rounded-2xl border border-hairline bg-panel px-8 py-12 text-center">
        <h2 className="text-xl font-medium tracking-tight">Still curious?</h2>
        <div className="flex gap-3">
          <Link
            href="/contact"
            className="rounded-full border border-hairline-strong px-6 py-3 text-sm text-muted transition-all hover:-translate-y-0.5 hover:border-white/25 hover:text-foreground"
          >
            Ask us anything
          </Link>
          <Link
            href="/learn"
            className="rounded-full bg-foreground px-6 py-3 text-sm font-medium text-background transition-all hover:-translate-y-0.5 hover:opacity-85"
          >
            Ask Lumen instead
          </Link>
        </div>
      </Reveal>
    </PageShell>
  );
}
